### ISSUE TITLE
Segfault launching template with Swagger using `x-amazon-apigateway-integration`

### ISSUE THREAD

**Issue by amagee** [awslabs/aws-sam-local#225]
Using aws-sam-local v0.2.4

`template.yaml` is from here: https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/inline_swagger/template.yaml

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple API Endpoint configured using Swagger specified inline and backed by a Lambda function
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
        StageName: prod
        DefinitionBody:
            swagger: 2.0
            info:
              title:
                Ref: AWS::StackName
            paths:
              "/get":
                get:
                  x-amazon-apigateway-integration:
                    httpMethod: POST
                    type: aws_proxy
                    uri:
                      Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyLambdaFunction.Arn}/invocations
                  responses: {}



            
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: s3://<bucket>/inline_swagger.zip
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /get
            Method: GET
            RestApiId: 
                Ref: MyApi
```

Output:

```
$ sam local start-api
2017/12/08 09:43:02 Connected to Docker 1.32
2017/12/08 09:43:02 Adding new API: MyApi
2017/12/08 09:43:02 Could not unmarshal integration data to ApiGatewayIntegration model
2017/12/08 09:43:02 No integration defined for method
2017/12/08 09:43:02 Fetching lambci/lambda:nodejs4.3 image for nodejs4.3 runtime...
nodejs4.3: Pulling from lambci/lambda
Digest: sha256:5de9009d6acde9585c0544e2d8078a83d4bce64c94ca5154747fe08476b0d7b1
Status: Image is up to date for lambci/lambda:nodejs4.3

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb08a88]

goroutine 1 [running]:
main.start(0xc420288a00)
        /root/go/src/github.com/awslabs/aws-sam-local/start.go:122 +0xe18
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.HandleAction(0xbdd000, 0xdd80d8, 0xc420288a00, 0xc42001de00, 0x0)
        /root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/app.go:487 +0x7c
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.Command.Run(0xdad42b, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0xdd5c5a, 0x3c9, 0x0, ...)
        /root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/command.go:207 +0xb72
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc420001d40, 0xc420288780, 0x0, 0x0)
        /root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/app.go:374 +0xacc
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.Command.startApp(0xdaa7d3, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xdd2037, 0x47, 0x0, ...)
        /root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/command.go:293 +0x8a3
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.Command.Run(0xdaa7d3, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xdd2037, 0x47, 0x0, ...)
        /root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/command.go:93 +0x14c7
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.(*App).Run(0xc420001ba0, 0xc420072240, 0x3, 0x3, 0x0, 0x0)
        /root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/app.go:250 +0x7d0
main.main()
        /root/go/src/github.com/awslabs/aws-sam-local/main.go:375 +0x24a2
```

Interestingly it seems to be the presence of the `x-amazon-apigateway-integration` specifically that causes the problem. I consistently segfault whenever there is any value for that key, regardless of what the value actually is. Removing `x-amazon-apigateway-integration` stops the segfault.

**Comment by deddu** [comment]
Facing the same issue on 0.24. 

```
 sam local start-api --template api.yaml
2017/12/12 12:38:22 Connected to Docker 1.32
2017/12/12 12:38:22 Adding new API: Api
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x168373b]

goroutine 1 [running]:
github.com/awslabs/aws-sam-local/router.(*AWSServerlessApi).Mounts(0xc4206e9530, 0x2, 0xc4204ade60, 0x13, 0x0, 0x0)
	/root/go/src/github.com/awslabs/aws-sam-local/router/api.go:51 +0xeb
github.com/awslabs/aws-sam-local/router.(*ServerlessRouter).AddAPI(0xc4206e9998, 0xc4205358c0, 0xc4206e98c0, 0x1)
	/root/go/src/github.com/awslabs/aws-sam-local/router/router.go:66 +0x42
main.start(0xc420553900)
	/root/go/src/github.com/awslabs/aws-sam-local/start.go:65 +0x659
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.HandleAction(0x17d56e0, 0x19d02a0, 0xc420553900, 0xc420168400, 0x0)
	/root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/app.go:487 +0x7c
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.Command.Run(0x19a5845, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x19cde2e, 0x3c9, 0x0, ...)
	/root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/command.go:207 +0xb72
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc420054b60, 0xc420553680, 0x0, 0x0)
	/root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/app.go:374 +0xacc
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.Command.startApp(0x19a2d5c, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x19ca20b, 0x47, 0x0, ...)
	/root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/command.go:293 +0x8a3
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.Command.Run(0x19a2d5c, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x19ca20b, 0x47, 0x0, ...)
	/root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/command.go:93 +0x14c7
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.(*App).Run(0xc4200549c0, 0xc42000e140, 0x5, 0x5, 0x0, 0x0)
	/root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/app.go:250 +0x7d0
main.main()
	/root/go/src/github.com/awslabs/aws-sam-local/main.go:375 +0x24a2
⋊> ~/w/f/r/s/api on master ⨯
```
Is it possible to explicitly pass a local swagger file in the CLI? I'm currently importing the swagger by AWS::Include from s3, and it would be way faster to test locally

**Comment by parsnips** [comment]
@deddu issue is different than the parent it seems.

Consider an stack.yaml that includes a swagger definition inlined via an `AWS::Include`:

```
Resources:
  API:
    Type: AWS::Serverless::Api
    Properties:
      StageName: something
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: !Sub "s3://${BucketName}/services/${Service}/packages/${Revision}/api.yaml"
```

the advantage of which, allows you to have the `Arn` of your lambdas to be substituted in the yaml file, eg:

```
x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SomeServerlessResource.Arn}/invocations
        passthroughBehavior: "when_no_match"
```

From looking at the `aws-sam-local` code, and my very limited understanding of cloudformation, this style of development is just not possible to support in sam-local :(
