### ISSUE TITLE
npm ERR! Failed at the aws-sam-local@0.2.4 postinstall script 'go-npm install'.

### ISSUE THREAD

**Issue by nickweavers** [awslabs/aws-sam-local#229]
I'm trying to install aws-sam-local under Windows Subsystem for Linux:

[npm-debug.log](https://github.com/awslabs/aws-sam-local/files/1555521/npm-debug.log)

nickw@DESKTOP-OREBB4V:~
$nodejs --version
v4.2.6
nickw@DESKTOP-OREBB4V:~
$npm --version
3.5.2

$sudo npm install -g aws-sam-local
loadDep:uuid → resolveWit ▌ ╢██████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

> aws-sam-local@0.2.4 postinstall /usr/local/lib/node_modules/aws-sam-local
> go-npm install

/usr/bin/env: ‘node’: No such file or directory
npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "aws-sam-local"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! aws-sam-local@0.2.4 postinstall: `go-npm install`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the aws-sam-local@0.2.4 postinstall script 'go-npm install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the aws-sam-local package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     go-npm install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs aws-sam-local
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls aws-sam-local
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nickw/npm-debug.log
nickw@DESKTOP-OREBB4V:~

**Comment by nickweavers** [comment]
uninstalled and reinstalled nodejs and npm and retried aws-sam-local install:

nickw@DESKTOP-OREBB4V:~
$curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -

## Installing the NodeSource Node.js v9.x repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://ppa.launchpad.net/ondrej/php/ubuntu xenial InRelease
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Get:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:6 https://download.docker.com/linux/ubuntu xenial InRelease
Get:7 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [678 kB]
Get:8 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [565 kB]
Get:9 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [16.2 kB]
Fetched 1,565 kB in 2s (777 kB/s)
Reading package lists... Done

## Confirming "xenial" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_9.x/dists/xenial/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
OK

## Creating apt sources list file for the NodeSource Node.js v9.x repo...

+ echo 'deb https://deb.nodesource.com/node_9.x xenial main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_9.x xenial main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://ppa.launchpad.net/ondrej/php/ubuntu xenial InRelease
Hit:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Hit:5 http://security.ubuntu.com/ubuntu xenial-security InRelease
Get:6 https://deb.nodesource.com/node_9.x xenial InRelease [4,622 B]
Hit:7 https://download.docker.com/linux/ubuntu xenial InRelease
Get:8 https://deb.nodesource.com/node_9.x xenial/main amd64 Packages [768 B]
Fetched 5,390 B in 2s (2,431 B/s)
Reading package lists... Done

## Run `apt-get install nodejs` (as root) to install Node.js v9.x and npm

nickw@DESKTOP-OREBB4V:~
$sudo apt-get install nodejs
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 12.8 MB of archives.
After this operation, 61.5 MB of additional disk space will be used.
Get:1 https://deb.nodesource.com/node_9.x xenial/main amd64 nodejs amd64 9.3.0-1nodesource1 [12.8 MB]
Fetched 12.8 MB in 6s (1,883 kB/s)
Selecting previously unselected package nodejs.
(Reading database ... 34588 files and directories currently installed.)
Preparing to unpack .../nodejs_9.3.0-1nodesource1_amd64.deb ...
Unpacking nodejs (9.3.0-1nodesource1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up nodejs (9.3.0-1nodesource1) ...
nickw@DESKTOP-OREBB4V:~
$node -v
v9.3.0
nickw@DESKTOP-OREBB4V:~
$sudo npm install -g aws-sam-local

\> aws-sam-local@0.2.4 postinstall /usr/lib/node_modules/aws-sam-local
\> go-npm install

/usr/lib/node_modules/aws-sam-local/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/aws-sam-local/bin'
    at Object.fs.mkdirSync (fs.js:905:18)
    at Function.sync (/usr/lib/node_modules/aws-sam-local/node_modules/mkdirp/index.js:71:13)
    at Object.install (/usr/lib/node_modules/aws-sam-local/node_modules/go-npm/bin/index.js:159:12)
    at Object.<anonymous> (/usr/lib/node_modules/aws-sam-local/node_modules/go-npm/bin/index.js:210:17)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aws-sam-local@0.2.4 postinstall: `go-npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aws-sam-local@0.2.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nickw/.npm/_logs/2017-12-13T14_01_57_271Z-debug.log

**Comment by sakelley-ucsd** [comment]
I'm seeing this same issue.

**Comment by KaiqueDamato** [comment]
I'm seeing this same issue to.

**Comment by dnavarrom** [comment]
this worked for me on Linux mint 18

sudo npm install -g go-npm
sudo npm install -g aws-sam-local

**Comment by axalix** [comment]
Nope, still doesn't work. Mint too.

**Comment by rsbjssdevops** [comment]
Still broken for me.

**Comment by nk2580** [comment]
for those who are interested it looks to be an issue with your permissions, in my case global packages can only be installed as root, this means anything that runs as a local user will fail when requesting access to /usr/lib/node_modules/ and go-npm is not run in sudo when installing. this means that you've got NPM setup with the wrong permissions
