### ISSUE TITLE
go explode on python 3.6 runtime

### ISSUE THREAD

**Issue by revmischa** [awslabs/aws-sam-local#262]
```
 $ sam local invoke
2018/01/14 04:17:55 Successfully parsed template.yml
2018/01/14 04:17:55 Connected to Docker 1.35
2018/01/14 04:17:55 Runtime image missing, will pull....
2018/01/14 04:17:55 Fetching lambci/lambda:python3.6 image for python3.6 runtime...
python3.6: Pulling from lambci/lambda

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15ca5f1]

goroutine 1 [running]:
github.com/awslabs/aws-sam-local/vendor/github.com/Nvveen/Gotty.(*TermInfo).GetAttribute(0x0, 0x19a1b9e, 0x3, 0xc420014ed0, 0x0, 0x0, 0xc420034800)
        /root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/Nvveen/Gotty/gotty.go:93 +0x131
github.com/awslabs/aws-sam-local/vendor/github.com/Nvveen/Gotty.(*TermInfo).Parse(0x0, 0x19a1b9e, 0x3, 0xc420014ed0, 0x1, 0x1, 0xc420657228, 0x10f32a5, 0xc420450000, 0xc420485e00)
        /root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/Nvveen/Gotty/parser.go:42 +0x5a
github.com/awslabs/aws-sam-local/vendor/github.com/docker/docker/pkg/jsonmessage.cursorUp(0x1e685c0, 0xc420098010, 0x1e67200, 0x0, 0x1)
        /root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/docker/docker/pkg/jsonmessage/jsonmessage.go:147 +0xe7
github.com/awslabs/aws-sam-local/vendor/github.com/docker/docker/pkg/jsonmessage.DisplayJSONMessagesStream(0x1e67f80, 0xc4206798c0, 0x1e685c0, 0xc420098010, 0x2, 0x1, 0x0, 0x0, 0x0)
        /root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/docker/docker/pkg/jsonmessage/jsonmessage.go:266 +0x3a1
main.NewRuntime(0x19a1595, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420139dd0, ...)
        /root/go/src/github.com/awslabs/aws-sam-local/runtime.go:193 +0xae4
main.invoke(0xc42014d2c0)
        /root/go/src/github.com/awslabs/aws-sam-local/invoke.go:102 +0x949
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.HandleAction(0x17d56e0, 0x19d0258, 0xc42014d2c0, 0xc420455f00, 0x0)
        /root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/app.go:487 +0x7c
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.Command.Run(0x19a366a, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x19cd332, 0x1b1, 0x0, ...)
        /root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/command.go:207 +0xb72
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc4204ce4e0, 0xc4200a2280, 0x0, 0x0)
        /root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/app.go:374 +0xacc
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.Command.startApp(0x19a2d5c, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x19ca20b, 0x47, 0x0, ...)
        /root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/command.go:293 +0x8a3
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.Command.Run(0x19a2d5c, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x19ca20b, 0x47, 0x0, ...)
        /root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/command.go:93 +0x14c7
github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli.(*App).Run(0xc4204ce340, 0xc42007a240, 0x3, 0x3, 0x0, 0x0)
        /root/go/src/github.com/awslabs/aws-sam-local/vendor/github.com/codegangsta/cli/app.go:250 +0x7d0
main.main()
        /root/go/src/github.com/awslabs/aws-sam-local/main.go:375 +0x24a2
/slack-urbandictionary
```

**Comment by PaulMaddox** [comment]
This is a known (but unsolved at this time) bug with some terminals.

For now, you can work around this by manually pulling the container image:
`docker pull lambci/lambda:python3.6`

Closing this issue, as we already have an open issue for this.

**Comment by revmischa** [comment]
ic ok. i am using multi-term with spacemacs
