### ISSUE TITLE
'Invalid endpoint' when Lambda invokes DynamoDB

### ISSUE THREAD

**Issue by MCLDG** [awslabs/aws-sam-local#48]
When my Lambda instantiates a boto3 session to the dynamoDB service, it fails with `Invalid endpoint: https://dynamodb..amazonaws.com`. Note the missing region in the URI (see stack trace below).

        dynamodb = boto3.resource('dynamodb')

I can force this to work by specifying a region:

        dynamodb = boto3.resource('dynamodb', region_name='ap-northeast-1' )

I cannot use the region in the Lamba env as it is blank:

        dynamodb = boto3.resource('dynamodb', region_name=os.environ['AWS_DEFAULT_REGION'] )

Lambda environment variables:
=======================

lambda env: 

`{'_HANDLER': 'calc-airmile-lambda.handler', 'AWS_LAMBDA_FUNCTION_VERSION': '$LATEST', 'LAMBDA_TASK_ROOT': '/var/task', 'AWS_REGION': '', 'LAMBDA_RUNTIME_DIR': '/var/runtime', 'PYTHONPATH': '/var/runtime', 'AWS_LAMBDA_FUNCTION_MEMORY_SIZE': '128', 'AWS_LAMBDA_FUNCTION_TIMEOUT': '3', 'AWS_DEFAULT_REGION': '', 'AWS_SAM_LOCAL': 'true', 'HOSTNAME': 'd479d39ddb0a', etc.}`

Stack trace
=========

```
Invalid endpoint: https://dynamodb..amazonaws.com: ValueError
Traceback (most recent call last):
  File "/var/task/calc-airmile-lambda.py", line 30, in handler
    dynamodb = boto3.resource('dynamodb', region_name=os.environ['AWS_DEFAULT_REGION'] )
  File "/var/runtime/boto3/__init__.py", line 92, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "/var/runtime/boto3/session.py", line 389, in resource
    aws_session_token=aws_session_token, config=config)
  File "/var/runtime/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/var/runtime/botocore/session.py", line 836, in create_client
    client_config=config, api_version=api_version)
  File "/var/runtime/botocore/client.py", line 71, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/var/runtime/botocore/client.py", line 281, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/var/runtime/botocore/args.py", line 79, in get_client_args
    timeout=(new_config.connect_timeout, new_config.read_timeout))
  File "/var/runtime/botocore/endpoint.py", line 273, in create_endpoint
    raise ValueError("Invalid endpoint: %s" % endpoint_url)
ValueError: Invalid endpoint: https://dynamodb..amazonaws.com

```

**Comment by sanathkr** [comment]
Ah, so region is not being passed to docker somehow.  How are you configuring your AWS credentials?

**Comment by MCLDG** [comment]
I've tried it with 2 credentials: one with a default region, one without. Result is the same. 

```
$ aws configure
AWS Access Key ID [****************etc]: 
AWS Secret Access Key [****************etc]: 
Default region name [us-east-1]: 
Default output format [None]: 
```

Error is:

```
Invalid endpoint: https://dynamodb..amazonaws.com: ValueError
Traceback (most recent call last):
  File "/var/task/calc-airmile-lambda.py", line 36, in handler
    dynamodb = boto3.resource('dynamodb' )
  File "/var/runtime/boto3/__init__.py", line 92, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "/var/runtime/boto3/session.py", line 389, in resource
    aws_session_token=aws_session_token, config=config)
  File "/var/runtime/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/var/runtime/botocore/session.py", line 836, in create_client
    client_config=config, api_version=api_version)
  File "/var/runtime/botocore/client.py", line 71, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/var/runtime/botocore/client.py", line 281, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/var/runtime/botocore/args.py", line 79, in get_client_args
    timeout=(new_config.connect_timeout, new_config.read_timeout))
  File "/var/runtime/botocore/endpoint.py", line 273, in create_endpoint
    raise ValueError("Invalid endpoint: %s" % endpoint_url)
ValueError: Invalid endpoint: https://dynamodb..amazonaws.com
```

**Comment by sanathkr** [comment]
I just tried with nodejs and python. I get AWS_REGION and AWS_DEFAULT_REGION populated with nodejs4.3 runtime, but not with python2.7. 

As a workaround, can you set region when you call `sam local`? 
Ex: `AWS_REGION=us-east-1 sam local start-api`

**Comment by nitzien** [comment]
Workaround worked for me.
