### ISSUE TITLE
invalid bind mount spec

### ISSUE THREAD

**Issue by gkamdar** [awslabs/aws-sam-local#93]
When trying to invoke "HelloWorld" from Samples I get the following error. How do I fix it. Below is the output. I am running Docker Toolbox on Windows7.

**C:\Users\gaurav_kamdar\go\src\github.com\awslabs\aws-sam-local\test\templates\sam-official-samples\hello_world>sam local invoke "HelloWorld" -e event.json**
2017/08/24 14:20:25 Successfully parsed template.yaml
←[34mINFO←[0m[0000] Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows
2017/08/24 14:20:25 Connected to Docker 1.28
←[34mINFO←[0m[0000] Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows
2017/08/24 14:20:25 Fetching lambci/lambda:nodejs4.3 image for nodejs4.3 runtime...
nodejs4.3: Pulling from lambci/lambda

←[1B84c367d8: Already exists
←[1Bf5aea2af: Already exists
←[1BDigest: sha256:fe7fd26840b4f06ba6626148f8bd234a6da21cd4fa2354dbc7c78be2d9bd5e3111kB/2.011kBB
Status: Downloaded newer image for lambci/lambda:nodejs4.3
2017/08/24 14:20:26 Invoking index.handler (nodejs4.3)
**2017/08/24 14:20:26 Could not invoke function: Error response from daemon: invalid bind mount spec "C:/Users/gaurav_kamdar/go/src/github.com/awslabs/aws-sam-local
/test/templates/sam-official-samples/hello_world:/var/task:ro": invalid volume specification: 'C:/Users/gaurav_kamdar/go/src/github.com/awslabs/aws-sam-local/test
/templates/sam-official-samples/hello_world:/var/task:ro'**

**Comment by sanathkr** [comment]
Are you using cygwin or git bash? Does this reproduce in cmd.exe or powershell?

**Comment by JohnHoward9** [comment]
I'm facing the same problem on Windows 10 Home 
2017/08/26 21:59:36 Could not invoke function: Error response from daemon: invalid bind mount spec "C:\\Users\\John\\AppData\\Local\\Temp\\aws-sam-local-1503781175721651700:/var/task:ro": invalid volume specification: 'C:\Users\John\AppData\Local\Temp\aws-sam-local-1503781175721651700:/var/task:ro'
aws-sam-local-1503781175721651700 exists on the local file system, but I assume SAM local is writing to that 

I'm using docker for the first time, so apologies if some of the responses are nonsense

I'm using git bash which was installed with the docker toolkit - I've tried cmd and powershell, but with both those I get

2017/08/27 10:06:53 Running AWS SAM projects locally requires Docker. Have you got it installed?

Is there a way of getting a list of shared directories from Docker Toolbox, all I could find in the docs was for listing shared directories in a container and the container is not running.  VirtualBox for default has a folder of name c:/Users and path \\?\c:\Users with auto-mount and full access.

**Comment by deividi86** [comment]
I am having the same problem on Docker toolbox and windows 7.

**Comment by deividi86** [comment]
I figured out that if you set `--docker-volume-basedir \c\Users` when invoking, it works.

**Comment by sanathkr** [comment]
Yeah, that's the solution. It is also documented in README file

**Comment by kaarthikeyansp** [comment]
kudos

**Comment by uvaisTrivecta** [comment]
I facing the same issue when trying to run the sample HelloWorld. I am running Docker Toolbox on Windows8.1 Pro. Sam Version 0.3.0 

**Output :  (with out --docker-volume-basedir)**

C:\Python27\Lib\site-packages\samcli\local\init\templates\cookiecutter-aws-sam-hello-java\{{cookiecutter.project_name}}>sam local start-api
2018-06-06 16:11:24 Mounting HelloWorldFunction at http://127.0.0.1:3000/hello [GET]
2018-06-06 16:11:24 You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template

2018-06-06 16:11:24  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
2018-06-06 16:11:30 Invoking helloworld.App::handleRequest (java8)
2018-06-06 16:11:30 Found credentials in shared credentials file: ~/.aws/credentials
2018-06-06 16:11:30 Decompressing C:\Python27\Lib\site-packages\samcli\local\init\templates\cookiecutter-aws-sam-hello-java\{{cookiecutter.project_name}}\target\HelloWorld-1.0.jar

Fetching lambci/lambda:java8 Docker container image......
2018-06-06 16:11:34 Mounting c:\users\lenovo2\appdata\local\temp\tmp2vg4ry as /var/task:ro inside runtime container
[2018-06-06 16:11:34,845] ERROR in app: Exception on /hello [GET]
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python27\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python27\lib\site-packages\samcli\local\apigw\service.py", line 161, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream, stderr=self.stderr)
  File "c:\python27\lib\site-packages\samcli\commands\local\lib\local_lambda.py", line 80, in invoke
    stdout=stdout, stderr=stderr)
  File "c:\python27\lib\site-packages\samcli\local\lambdafn\runtime.py", line 83, in invoke
    self._container_manager.run(container)
  File "c:\python27\lib\site-packages\samcli\local\docker\manager.py", line 61, in run
    container.create()
  File "c:\python27\lib\site-packages\samcli\local\docker\container.py", line 110, in create
    real_container = self.docker_client.containers.create(self._image, **kwargs)
  File "c:\python27\lib\site-packages\docker\models\containers.py", line 824, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "c:\python27\lib\site-packages\docker\api\container.py", line 410, in create_container
    return self.create_container_from_config(config, name)
  File "c:\python27\lib\site-packages\docker\api\container.py", line 421, in create_container_from_config
    return self._result(res, True)
  File "c:\python27\lib\site-packages\docker\api\client.py", line 231, in _result
    self._raise_for_status(response)
  File "c:\python27\lib\site-packages\docker\api\client.py", line 227, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "c:\python27\lib\site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
APIError: 500 Server Error: Internal Server Error ("invalid volume specification: 'c:\users\lenovo2\appdata\local\temp\tmp2vg4ry:/var/task:ro'")
2018-06-06 16:11:34 127.0.0.1 - - [06/Jun/2018 16:11:34] "GET /hello HTTP/1.1" 502 -
2018-06-06 16:11:35 127.0.0.1 - - [06/Jun/2018 16:11:35] "GET /favicon.ico HTTP/1.1" 403 -


**Output :  (with --docker-volume-basedir)**
C:\Python27\Lib\site-packages\samcli\local\init\templates\cookiecutter-aws-sam-hello-java\{{cookiecutter.project_name}}>sam local start-api --docker-volume-basedir \c\Users
2018-06-06 16:15:10 Mounting HelloWorldFunction at http://127.0.0.1:3000/hello [GET]
2018-06-06 16:15:10 You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
2018-06-06 16:15:10  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
2018-06-06 16:15:14 Invoking helloworld.App::handleRequest (java8)
2018-06-06 16:15:14 Found credentials in shared credentials file: ~/.aws/credentials

Fetching lambci/lambda:java8 Docker container image......
2018-06-06 16:15:17 Mounting C:\c\Users\target\HelloWorld-1.0.jar as /var/task:ro inside runtime container
[2018-06-06 16:15:18,585] ERROR in app: Exception on /hello [GET]
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\python27\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\python27\lib\site-packages\samcli\local\apigw\service.py", line 161, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream, stderr=self.stderr)
  File "c:\python27\lib\site-packages\samcli\commands\local\lib\local_lambda.py", line 80, in invoke
    stdout=stdout, stderr=stderr)
  File "c:\python27\lib\site-packages\samcli\local\lambdafn\runtime.py", line 83, in invoke
    self._container_manager.run(container)
  File "c:\python27\lib\site-packages\samcli\local\docker\manager.py", line 61, in run
    container.create()
  File "c:\python27\lib\site-packages\samcli\local\docker\container.py", line 110, in create
    real_container = self.docker_client.containers.create(self._image, **kwargs)
  File "c:\python27\lib\site-packages\docker\models\containers.py", line 824, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "c:\python27\lib\site-packages\docker\api\container.py", line 410, in create_container
    return self.create_container_from_config(config, name)
  File "c:\python27\lib\site-packages\docker\api\container.py", line 421, in create_container_from_config
    return self._result(res, True)
  File "c:\python27\lib\site-packages\docker\api\client.py", line 231, in _result
    self._raise_for_status(response)
  File "c:\python27\lib\site-packages\docker\api\client.py", line 227, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "c:\python27\lib\site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
APIError: 500 Server Error: Internal Server Error ("invalid volume specification: 'C:\c\Users\target\HelloWorld-1.0.jar:/var/task:ro'")
2018-06-06 16:15:18 127.0.0.1 - - [06/Jun/2018 16:15:18] "GET /hello HTTP/1.1" 502 -
2018-06-06 16:15:18 127.0.0.1 - - [06/Jun/2018 16:15:18] "GET /favicon.ico HTTP/1.1" 403 -
